<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Sed nec mi quis ligula consectetur viverra. Suspendisse potenti.
            Nulla id laoreet tortor. Quisque a convallis neque. Sed vitae 
            vehicula ipsum. Interdum et malesuada fames ac ante ipsum primis in faucibus.
        </p>
    </li>
</ul>
