<table class="data-table" style="width:100%;" cellpadding="10" cellspacing="10">
    <tr>
        <td style="width:50%;">
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4>General Details</h4>
                </div>
                <div class="fieldset fieldset-wide">
                    <table cellspacing="0" class="form-list">
                        <tbody>
                            <tr>
                                <td class="label"><label>Proposal ID</label></td>
                                <td class="value"><strong><?php echo $this->getApplication()->getProposalId(); ?></strong></td>
                            </tr>
                            <tr>
                                <td class="label"><label>Proposal Status</label></td>
                                <td class="value"><strong><?php echo $this->getOrder()->getStatusLabel(); ?></strong></td>
                            </tr>
                            <tr>
                                <td class="label"><label>Application Placed</label></td>
                                <td class="value"><strong><?php echo $this->getApplication()->getCreatedAt(); ?></strong></td>
                            </tr>
                            <tr>
                                <td class="label"><label>Application Updated</label></td>
                                <td class="value"><strong><?php echo $this->getApplication()->getUpdatedAt(); ?></strong></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </td>
        <td style="width:50%;">
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4>Customer Address</h4>
                </div>
                <div class="fieldset fieldset-wide">
                    <?php if ( $this->hasAddress() ) { ?>
                        <table cellspacing="0" class="form-list">
                            <tbody>
                                
                                <?php /* house number */ ?>
                                <?php if ( $this->getAddress()->getHouseNumber() ) { ?>
                                    <tr>
                                        <td class="label"><label>House Number</label></td>
                                        <td class="value"><strong><?php echo $this->getAddress()->getHouseNumber(); ?></strong></td>
                                    </tr>
                                <?php } ?>
                                
                                <?php /* house name */ ?>
                                <?php if ( $this->getAddress()->getHouseName() ) { ?>
                                    <tr>
                                        <td class="label"><label>House Name</label></td>
                                        <td class="value"><strong><?php echo $this->getAddress()->getHouseName(); ?></strong></td>
                                    </tr>
                                <?php } ?>
                                
                                <?php /* flat */ ?>
                                <?php if ( $this->getAddress()->getFlat() ) { ?>
                                    <tr>
                                        <td class="label"><label>Flat</label></td>
                                        <td class="value"><strong><?php echo $this->getAddress()->getFlat(); ?></strong></td>
                                    </tr>
                                <?php } ?>
                                
                                <?php /* street */ ?>
                                <?php if ( $this->getAddress()->getStreet() ) { ?>
                                    <tr>
                                        <td class="label"><label>Street</label></td>
                                        <td class="value"><strong><?php echo $this->getAddress()->getStreet(); ?></strong></td>
                                    </tr>
                                <?php } ?>
                                
                                <?php /* district */ ?>
                                <?php if ( $this->getAddress()->getDistrict() ) { ?>
                                    <tr>
                                        <td class="label"><label>District</label></td>
                                        <td class="value"><strong><?php echo $this->getAddress()->getDistrict(); ?></strong></td>
                                    </tr>
                                <?php } ?>
                                
                                <?php /* town */ ?>
                                <?php if ( $this->getAddress()->getTown() ) { ?>
                                    <tr>
                                        <td class="label"><label>Town</label></td>
                                        <td class="value"><strong><?php echo $this->getAddress()->getTown(); ?></strong></td>
                                    </tr>
                                <?php } ?>
                                
                                <?php /* county */ ?>
                                <?php if ( $this->getAddress()->getCounty() ) { ?>
                                    <tr>
                                        <td class="label"><label>County</label></td>
                                        <td class="value"><strong><?php echo $this->getAddress()->getCounty(); ?></strong></td>
                                    </tr>
                                <?php } ?>
                                
                                <?php /* postcode */ ?>
                                <?php if ( $this->getAddress()->getPostcode() ) { ?>
                                    <tr>
                                        <td class="label"><label>Postcode</label></td>
                                        <td class="value"><strong><?php echo $this->getAddress()->getPostcode(); ?></strong></td>
                                    </tr>
                                <?php } ?>
                            </tbody>
                        </table>
                    <?php } else { ?>
                        <p>No address stored.</p>
                    <?php } ?>
                </div>
            </div>
        </td>
    </tr>
    <tr>
        <td style="width:50%;">
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4>Checklist Conditions</h4>
                </div>
                <div class="fieldset fieldset-wide">
                    <?php if ( $this->hasChecklists() ) { ?>
                        <table cellspacing="0" class="form-list">
                            <tbody>
                                <tr>
                                    <td class="value">&nbsp;</td>
                                    <td class="value"><strong>Type</strong></td>
                                    <td class="value"><strong>Status</strong></td>
                                    <td class="value"><strong>Satisfied</strong></td>
                                    <td class="value"><strong>Satisfied On</strong></td>
                                </tr>
                                <?php $i = 0; foreach ( $this->getChecklists() as $checklist ) { ?>
                                    <tr>
                                        <td class="value"><?php echo ++$i; ?>.</td>
                                        <td class="value"><label><?php echo $checklist->getType(); ?></label></td>
                                        <td class="value"><strong><?php echo $checklist->getStatus(); ?></strong></td>
                                        <td class="value"><strong><?php echo $checklist->getSatisfied() ? $this->__('Yes') : $this->__('No'); ?></strong></td>
                                        <td class="value"><strong><?php echo $this->getChecklistSatisfiedOn($checklist); ?></strong></td>
                                    </tr>
                                <?php } ?>
                            </tbody>
                        </table>
                    <?php } else { ?>
                        <p>No checklist conditions stored.</p>
                    <?php } ?>
                </div>
            </div>
        </td>
        <td style="width:50%;">
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4>Snags</h4>
                </div>
                <div class="fieldset fieldset-wide">
                    <?php if ( $this->hasSnags() ) { ?>
                        <table cellspacing="0" class="form-list">
                            <tbody>
                                <tr>
                                    <td class="value">&nbsp;</td>
                                    <td class="value"><strong>Type</strong></td>
                                    <td class="value"><strong>Description</strong></td>
                                    <td class="value"><strong>Note</strong></td>
                                </tr>
                                <?php $i = 0; foreach ( $this->getSnags() as $snag ) { ?>
                                    <tr>
                                        <td class="value"><?php echo ++$i; ?>.</td>
                                        <td class="value"><?php echo $snag->getType(); ?></td>
                                        <td class="value"><?php echo $snag->getDescription(); ?></td>
                                        <td class="value"><?php echo $snag->getNote(); ?></td>
                                    </tr>
                                <?php } ?>
                            </tbody>
                        </table>
                    <?php } else { ?>
                        <p>No snags stored.</p>
                    <?php } ?>
                </div>
            </div>
        </td>
    </tr>
</table>


